import Product from "./product";
import Category from "./category";

// Initialize an array of products
const products: Product[] = [
  {
    name: "Croissant",
    description: "Buttery flaky pastry",
    isPerishable: true,
    expiryDate: new Date("2024-03-15"),
    category: Category.Bakery,
    price: 2.5,
    onSpecial: false,
  },
  {
    name: "Apple",
    description: "Sweet and juicy fruit",
    isPerishable: true,
    expiryDate: new Date("2024-03-12"),
    category: Category.Fruit,
    price: 1.0,
    onSpecial: true,
  },
  {
    name: "Frozen Pizza",
    description: "Delicious ready-to-bake pizza",
    isPerishable: false,
    expiryDate: new Date("2025-12-31"),
    category: Category.Frozen,
    price: 5.99,
    onSpecial: false,
  },
  {
    name: "Toilet Paper",
    description: "Soft and absorbent",
    isPerishable: false,
    expiryDate: new Date("2099-12-31"),
    category: Category.Household,
    price: 7.99,
    onSpecial: true,
  },
  {
    name: "Chicken Breast",
    description: "Lean white meat",
    isPerishable: true,
    expiryDate: new Date("2024-03-10"),
    category: Category.Meat,
    price: 4.5,
    onSpecial: false,
  },
  {
    name: "Carrots",
    description: "Sweet and crunchy vegetables",
    isPerishable: true,
    expiryDate: new Date("2024-03-14"),
    category: Category.Vegetables,
    price: 0.99,
    onSpecial: false,
  },
  {
    name: "Baguette",
    description: "Long and crusty French bread",
    isPerishable: true,
    expiryDate: new Date("2024-03-15"),
    category: Category.Bakery,
    price: 1.99,
    onSpecial: true,
  },
  {
    name: "Banana",
    description: "Yellow curved fruit",
    isPerishable: true,
    expiryDate: new Date("2024-03-10"),
    category: Category.Fruit,
    price: 0.5,
    onSpecial: false,
  },
  {
    name: "Ice Cream",
    description: "Creamy frozen dessert",
    isPerishable: true,
    expiryDate: new Date("2024-03-31"),
    category: Category.Frozen,
    price: 3.49,
    onSpecial: true,
  },
  {
    name: "Laundry Detergent",
    description: "Powerful cleaning agent for clothes",
    isPerishable: false,
    expiryDate: new Date("2025-12-31"),
    category: Category.Household,
    price: 9.99,
    onSpecial: false,
  },
  {
    name: "Ground Beef",
    description: "Minced meat from beef",
    isPerishable: true,
    expiryDate: new Date("2024-03-09"),
    category: Category.Meat,
    price: 6.99,
    onSpecial: true,
  },
  {
    name: "Lettuce",
    description: "Crisp green leafy vegetable",
    isPerishable: true,
    expiryDate: new Date("2024-03-13"),
    category: Category.Vegetables,
    price: 1.29,
    onSpecial: false,
  },
  {
    name: "Bagel",
    description: "Ring-shaped bread roll",
    isPerishable: true,
    expiryDate: new Date("2024-03-15"),
    category: Category.Bakery,
    price: 0.75,
    onSpecial: false,
  },
  {
    name: "Orange",
    description: "Round citrus fruit",
    isPerishable: true,
    expiryDate: new Date("2024-03-11"),
    category: Category.Fruit,
    price: 0.75,
    onSpecial: false,
  },
  {
    name: "Frozen Vegetables Mix",
    description: "Assorted frozen vegetables",
    isPerishable: false,
    expiryDate: new Date("2025-12-31"),
    category: Category.Frozen,
    price: 2.99,
    onSpecial: false,
  },
  {
    name: "Dish Soap",
    description: "Liquid soap for washing dishes",
    isPerishable: false,
    expiryDate: new Date("2025-12-31"),
    category: Category.Household,
    price: 3.49,
    onSpecial: true,
  },
  {
    name: "Salmon Fillet",
    description: "Fillet of salmon fish",
    isPerishable: true,
    expiryDate: new Date("2024-03-08"),
    category: Category.Meat,
    price: 9.99,
    onSpecial: false,
  },
  {
    name: "Broccoli",
    description: "Nutritious green vegetable",
    isPerishable: true,
    expiryDate: new Date("2024-03-14"),
    category: Category.Vegetables,
    price: 2.49,
    onSpecial: false,
  },
  {
    name: "Chocolate Chip Cookies",
    description: "Homemade cookies with chocolate chips",
    isPerishable: true,
    expiryDate: new Date("2024-03-17"),
    category: Category.Bakery,
    price: 3.99,
    onSpecial: false,
  },
  {
    name: "Grapes",
    description: "Small sweet berries",
    isPerishable: true,
    expiryDate: new Date("2024-03-11"),
    category: Category.Fruit,
    price: 2.99,
    onSpecial: true,
  },
  {
    name: "Frozen French Fries",
    description: "Thin potato fries ready to cook",
    isPerishable: false,
    expiryDate: new Date("2025-12-31"),
    category: Category.Frozen,
    price: 1.99,
    onSpecial: false,
  },
  {
    name: "Paper Towels",
    description: "Absorbent towels for cleaning",
    isPerishable: false,
    expiryDate: new Date("2099-12-31"),
    category: Category.Household,
    price: 4.99,
    onSpecial: true,
  },
  {
    name: "Ground Turkey",
    description: "Minced meat from turkey",
    isPerishable: true,
    expiryDate: new Date("2024-03-09"),
    category: Category.Meat,
    price: 5.49,
    onSpecial: false,
  },
  {
    name: "Blueberry Muffin",
    description: "Moist muffin with blueberries",
    isPerishable: true,
    expiryDate: new Date("2024-03-16"),
    category: Category.Bakery,
    price: 1.99,
    onSpecial: false,
  },
  {
    name: "Orange",
    description: "Citrus fruit with vitamin C",
    isPerishable: true,
    expiryDate: new Date("2024-03-11"),
    category: Category.Fruit,
    price: 0.75,
    onSpecial: false,
  },
  {
    name: "Frozen Fish Fillets",
    description: "Fresh frozen fish fillets",
    isPerishable: true,
    expiryDate: new Date("2025-12-31"),
    category: Category.Frozen,
    price: 8.49,
    onSpecial: true,
  },
  {
    name: "Laundry Detergent",
    description: "Powerful cleaning detergent",
    isPerishable: false,
    expiryDate: new Date("2025-12-31"),
    category: Category.Household,
    price: 12.99,
    onSpecial: false,
  },
  {
    name: "Pork Chop",
    description: "Tender pork chop",
    isPerishable: true,
    expiryDate: new Date("2024-03-09"),
    category: Category.Meat,
    price: 6.75,
    onSpecial: false,
  },
  {
    name: "Broccoli",
    description: "Nutritious green vegetable",
    isPerishable: true,
    expiryDate: new Date("2024-03-13"),
    category: Category.Vegetables,
    price: 1.49,
    onSpecial: true,
  },
  {
    name: "Ice Cream",
    description: "Creamy frozen dessert",
    isPerishable: true,
    expiryDate: new Date("2024-04-30"),
    category: Category.Frozen,
    price: 4.99,
    onSpecial: false,
  },
];

export default products;
